name: Build & Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.6.x
      - run: npm ci
      - name: Tests
        run: npm test
        env:
          JWT_SECRET: TestingSecretPassword
      - name: Build
        run: npm run build --if-present
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vetapplication"
          heroku_email: "danielnavram@gmail.com"
